### ISSUE TITLE
Changing the selected link colour

### ISSUE THREAD

**Issue by jamesb93** [alex-shpak/hugo-book#104]
Hi Alex,

I can't for the life of me figure out how to change the colour of selected link. I've modified the CSS of the theme to get the link colour i'd prefer, but it does not apply to the currently selected page from the nav bar. How can I change this?

<img width="909" alt="image" src="https://user-images.githubusercontent.com/13281862/69892245-6f342100-12fb-11ea-898f-70e5b4b5fbde.png">

**Comment by alex-shpak** [comment]
Hi!
Active menu items has `class="active"` on them, so you need something like
```scss
.book-menu a.active {
  color: #000
}
```

in `assets/_custom.scss`

**Comment by alex-shpak** [comment]
Alternatively you can change with `assets/_variables.scss`
```scss
$color-link: #05b;
$color-visited-link: #8440f1;
```

**Comment by jamesb93** [comment]
Thanks for getting back to me on a fix Alex. Unfortunately neither of your suggested workarounds allowed me to change the active colour. You can see them made here:

https://github.com/jamesb93/huddersfield-creative-coding/tree/update

and the rendered website:

https://huddersfield-creative-coding.onrender.com/posts/creative-version-control/

Also, I have noticed that when I click  on a blog post the sidebar moves upwards slightly. Is that intended?

**Comment by jamesb93** [comment]
Actually, I pulled in your latest changes for the theme and it fixed the link issue. 

I did have some problems integrating your changes though - it does seem like you have added or moved some of the scss around. I managed to tweak it back to what I had in order to get it to compile but hey there you go. Any chance you could take a look at the issue of the sidebar moving when I click on a  blog post?

**Comment by alex-shpak** [comment]
I had a glance at your repo. I would suggest that you don't need to maintain a fork of theme.
You can override files, including `_custom.scss` and `_variables.scss`, at https://github.com/jamesb93/huddersfield-creative-coding by just creating `assets` folder there.
As well as `layouts/partials/docs/inject/`

It will also make it easier to update.

Regarding sidebar, I think it's due to appearing scroll bar on right, which pushes all content left, it's normal. (If it is what you mean).

Check here example of dark theme:
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_variables.scss
https://github.com/alex-shpak/hugo-book/blob/master/assets/plugins/_dark.scss

**Comment by jamesb93** [comment]
Okay, thanks for your input. I think for this current project I'll keep my own fork maintained but I have a new one (using the same theme) where I'll just keep it stock. Thank you for all your hard work on this :)
