### ISSUE TITLE
Change color of SVG menu button

### ISSUE THREAD

**Issue by IdentityArchitecture** [alex-shpak/hugo-book#111]
Hello!

I'm sorry if this is a dumb question, but I've been trying to figure this out for weeks, and I'm stuck:

How would I change the color of the SVG menu button? As you can see, it's completely transparent and not visible on my website: https://ink.university/

Thank you for any help you can provide.

The Architect

**Comment by alex-shpak** [comment]
Hi!
Your icon is not transparent, it's just very small.
![image](https://user-images.githubusercontent.com/5515443/70423746-661b2080-1a6e-11ea-8d12-59371a8f9c89.png)

Probably because of this style: 
![image](https://user-images.githubusercontent.com/5515443/70423802-7fbc6800-1a6e-11ea-9bbe-f3953f4097b4.png)

To answer coloring question, simplest would be to replace icons with white version of them in `static/svg`. Icons are coming from https://material.io/resources/icons/ set

Alternatively you can apply filter to image, note that it has limited browser support
```
.book-footer img, header img {
  filter: brightness(0) invert(1);
}
```

**Comment by alex-shpak** [comment]
Closing this issue, hope your problem is solved.
Write comment here if you want me to re-open it.
