### ISSUE TITLE
How about tags publishing with the spacing word.

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#132]
My post has a tag with the spacing word such as "Platform Business". The tag isn't shown. 
So, I fixed to Platform Business. However, still not shown. I retry to change Business, Platform and then successful.

I think that the tag with the spacing word is not working.

Could you check?

**Comment by alex-shpak** [comment]
Hi!
Let's see, I never tested tags with spaces.

**Comment by alex-shpak** [comment]
https://discourse.gohugo.io/t/problem-with-upper-case-and-spaces-in-tags/15846/7
Related.

**Comment by alex-shpak** [comment]
I made some adjustments, should work for simple cases, please test it with korean language

**Comment by noweaver** [comment]
Always, I can test! ^^

The tags of right side bar is working well. But The tag in post's page is not shown in Korean.

tags: ["Hugo", "설치"] 

"설치" indicate https://translate.google.com/?hl=ko#view=home&op=translate&sl=ko&tl=en&text=%EC%84%A4%EC%B9%98

Anyway, Korean tag is now working.

**Comment by alex-shpak** [comment]
Hi!
It looks like missing support on hugo side. 
The URL to tag page is processed with `urlize` function in order to convert string to 'url like' text. And that seems to remove korean symbols.

Unfortunately I can't fix that without support from hugo (or ugly hacks), we might open discussion thread in their repo.

**Comment by alex-shpak** [comment]
Closing in favour of #140
