### ISSUE TITLE
How to add a comment service like the Disqus

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#133]
Alex,

I added a comment service like the Disqus service in footer.html. 

I seemed to be successful in my task but soon disappointed. Even though it is successful in each post, the front page also showed.

https://noweaver.github.io/posts/Misc/2014-03-10_migrate-from-jekyll/#a-practical-example-in-a-diff
This URL is shown correctly. :) 

https://noweaver.github.io/
But the main or front-page is not working.

I added the code in footer.html like following as;

```
<!-- Ryan modified -->
<!--
{{ if (default true (default .Site.Params.BookDisqus .Params.bookDisqus)) }}
 {{ template "_internal/disqus.html" . }} 
{{ end }} 
-->

<br>
<hr color="#D6D6D6" size=0>
<script src="https://utteranc.es/client.js" 
        repo="noweaver/noweaver-comment" 
        issue-term="[##_article_rep_link" 
        theme="github-light" 
        crossorigin="anonymous" 
        async> 
</script>

```

**Comment by alex-shpak** [comment]
Hi!
There is [Disqus support in Hugo](https://gohugo.io/content-management/comments/#add-disqus), and in theme as well, thanks to [PR](https://github.com/alex-shpak/hugo-book/pull/120)

To enable set `disqusShortname: yourdiscussshortname` site variable.

I guess if you want other service, you can replace [this line](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/footer.html#L30) with your template. 🤔 Maybe I should put comments in separate partial.

As for home page, since you have custom template, you will need to add it after this line
https://github.com/noweaver/noweaver/blob/master/layouts/home.html#L19

**Comment by alex-shpak** [comment]
I made some changes to comments, so now you can override `layouts/partials/docs/comments.html` and put `utteranc` template there without touching theme.

**Comment by noweaver** [comment]
Alex, Thanx,
'Cause I am a rookie about the static blog, I still don't know your guide. 

I just want to show the comment on the only post page except for the front-page.

https://noweaver.github.io/ 
You can see the Disqus comment service on the front-page. I don't want to show the comment service on the pagination's below of the font-page.

**Comment by alex-shpak** [comment]
Hi!
If you want to have comments only on regular pages do this:

```tpl
{{ if .Content }}
  {{ "include_your_comments_code_here" }}
{{ end }}
```

This will render that block only for pages with content.
I'm preparing big update now, that will include that `if` as well.

**Comment by noweaver** [comment]
```
<!-- This partial can be replaced to support other commenting engines -->
{{ if .Content }}
    {{ template "_internal/disqus.html" . }}
{{ end }}
```

I solved and thanks

**Comment by alex-shpak** [comment]
Closing then :)
