### ISSUE TITLE
how do I get /posts to show up on the menu?

### ISSUE THREAD

**Issue by rhuang** [alex-shpak/hugo-book#137]
I'm looking at the demo: https://themes.gohugo.io//theme/hugo-book/

In the sample content: https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/menu/index.md

I see you have `[Blog]({{< relref "/posts" >}})` in last item, but it doesn't actually show up in the menu. Can you help me understand why?

**Comment by alex-shpak** [comment]
Hi!
`content/menu/index.md` is example file for leaf bundle menu mode.

There are 2 menu modes in theme:
1: That renders file tree as menu (which is displayed in demo)
2: That renders markdown file from leaf bundle: [more](https://gohugo.io/content-management/page-bundles/#leaf-bundles)

In order to enable leaf bundle menu set `BookMenuBundle = '/menu'` 

https://github.com/alex-shpak/hugo-book#menu

**Comment by noweaver** [comment]
In config.toml file, BookMenuBundle = '/menu'

**Comment by rhuang** [comment]
Thanks guys, this makes sense now! Closing.
