### ISSUE TITLE
Can you make katex enable with $$？

### ISSUE THREAD

**Issue by WingLim** [alex-shpak/hugo-book#164]
I am using Typora to write markdown.
It can render latex in real time with `$$ some latex code $$`
But if I using the `hugo-book` theme, I have to use the shortcode `{{< katex >}}{{< /katex >}}`, It is inconvenient.
And it couldn't show the formula in Typora too.
So, if there is any possible to render latex by using $$ in `hugo-book` theme？

**Comment by alex-shpak** [comment]
Hi!
Katex is not included into every page because it's quite heavy, so `{{< katex >}}` shortcode is used to activate library on page.

You can do some trick: Once `KaTeX` is activated you can use `$$` or `\\(` `\\)` in markdown as it is.
So put `{{< katex />}}` I the beginning of file where you want to have it.

**Comment by WingLim** [comment]
It work for me, thanks a lot.

**Comment by ikingye** [comment]
I put `{{< katex />}}` in the beginning of file, then

`$$ 2^3 $$` (block) works well, but `$ 2^3 $` (inline) not work.
