### ISSUE TITLE
Search is not working on demo site

### ISSUE THREAD

**Issue by amuraru** [alex-shpak/hugo-book#193]

**Comment by alex-shpak** [comment]
Hi!
Yes, unfortunately search doesn't work on https://themes.gohugo.io/
This is due to setup of themes website: [Reference](https://github.com/gohugoio/hugoThemes#common-permalink-issues).

In order to make it work JS script have to be linked with absolute URL, but I try to keep relative links everywhere in theme to make it more portable. I think it doesn't worth using absolute URL only in one place.
