### ISSUE TITLE
failed to click the tab on mobile web

### ISSUE THREAD

**Issue by noticebo** [alex-shpak/hugo-book#198]
Hi,

When I deployed my website, I found that the tab as the red color marked failed to be clicked. How to fix it? thank you.

you could visit my website by http://p4986n.coding-pages.com/ on mobile phone.

![image](https://user-images.githubusercontent.com/62462953/79248538-8b9db800-7eae-11ea-88fb-ab74eda2309c.jpg)

**Comment by alex-shpak** [comment]
Hi!
Something is wrong in html produced. Maybe due to some customization? If I look at your page it looks like:
![image](https://user-images.githubusercontent.com/5515443/79250165-95a7c280-7e7e-11ea-9ef3-cf8d6c951c9c.png)

But should be:
![image](https://user-images.githubusercontent.com/5515443/79250115-84f74c80-7e7e-11ea-966e-aad06c541a4b.png)

Note `<label for=menu-control` which got out of `book-page` class, causing it overlay menu in mobile view.

**Comment by noticebo** [comment]
thanks. I delete the public folder and re hugo -t book. it works now.
