### ISSUE TITLE
Multi-level submenus

### ISSUE THREAD

**Issue by sanghapark** [alex-shpak/hugo-book#20]
Is there any way to make subcategories in a category? Currently, I am using BookMenuBundle  like below.
/content/menu/index.md 
- **Math**
  - **Calculus**
     - [Basics]({{< ref "/docs/math/calculus/basics.md" >}})
     - [Advanced]({{< ref "/docs/math/calculus/advanced.md" >}})
  - **Statistics**
     - [Basics]({{< ref "/docs/math/statistics/basics.md" >}})
- **Machine Learning**
  - **Projects**
    - [Keyword Extraction]({{< ref "/docs/ml/keywordextraction.md" >}})
  - **Theories**
    - [Decision Theory]({{< ref "/docs/ml/monk/01_decision_theory.md" >}})
- **Deep Learning**
  - [Backprop]({{< ref "/docs/deeplearning/backprop.md" >}})
- **Linux**

"Projects" and "Theories" are child categories of "Machine Learning" category.  
I want to show this hierarchical structure of menu in the sidebar. It would be really nice if categories are expandable/collapsible by clicking.

**Comment by alex-shpak** [comment]
Hi!
As for first part, looks like `Keyword Extraction` and `Decision Theory` are falling under parent section due to having only 2 spaces indentation.
Try to use 4 spaces instead, see [this](https://markdown-guide.readthedocs.io/en/latest/basics.html#lists-nested)

About collapsable menu:
So far I kept theme JS free, I will think about way to do collapsing, but can't promise adding this feature if it will require JS.

**Comment by alex-shpak** [comment]
Feel free to reopen if you need some more assistance.
Closing for now.
