### ISSUE TITLE
question about "dummy" in layouts/_default/single.html

### ISSUE THREAD

**Issue by rmflight** [alex-shpak/hugo-book#239]
I know this is more a question than an actual issue, but in the `layouts/_default`, the `single.html` only has 

    {{ define "dummy" }}{{ end }}

Does this make it basically take only the content of `baseof.html`, and nothing else? 

Therefore, if I want to define something else for the site index page, I should make a new page in `layouts/_default/single.html` with the layout I want?

I'm basically trying to figure out how to define my layout for the `index.html` page similarly to how I modify `layouts/posts/single.html`.

**Comment by alex-shpak** [comment]
Hi! Yes, since there is no difference between list/single template just `baseof` is used, but seems like without having content in list/single file hugo skips template as like it doesn't exist.

To change site index pages best would be to create own type of page:
- Create `layouts/home/single.html` with content you want. (without overwriting `baseof.html` it will inherit from `_default`)
- Create page `content/_index.md`
- Put frontmater setting kind of page to `home`
```
---
type: home
---
```

I write it without testing, so some small tweaks might be needed.
