### ISSUE TITLE
Images not rendering unless in a nested directory

### ISSUE THREAD

**Issue by thedavidharris** [alex-shpak/hugo-book#256]
First off, theme looks great, perfect for our use case.

Noticed that in order to get images to render, they had to be nested one folder deeper than the current directory, i.e.:

```
PageName
├── PageName
 │   ├── Image1.png
 │   └── Image2.png
 ├── PageName.md
```

Where the image in PageName.md references the image like `![My Image](Image1.png)`

Is this by design or is it incidentally inserting that extra level? Ideally in our case it wouldn't, so that the Github markdown still renders correctly, so it looks like:

```
PageName
├── Image1.png
│── Image2.png
├── PageName.md
```

**Comment by alex-shpak** [comment]
HI!
It happens due to how hugo generate URLs

For example, file `PageName.md` will give you url `http://localhost:1313/PageName/`, so image referenced as `image1.png` from that page gives you `http://localhost:1313/PageName/image1.png`, that is why folder requirement.

You can `PageName.md` file to `PageName/_index.md`, then images will be in same folder.

**Comment by thedavidharris** [comment]
ahh okay had a hard time tracking that down! apprecaite it.
