### ISSUE TITLE
[Feature] Copy button in code blocks

### ISSUE THREAD

**Issue by eugene-krivobokov** [alex-shpak/hugo-book#281]
Hi! It'd be nice to have a copy button in code blocks.

Example: https://github.com/avito-tech/avito-android/pull/594

![](https://user-images.githubusercontent.com/1104540/95683849-591f0e80-0bf6-11eb-983e-785a4c6f429f.gif)

**Comment by alex-shpak** [comment]
Hi!
There is https://github.com/alex-shpak/hugo-book/tree/feature/copy branch, but it very WIP. I don't want to include large `clipboardjs` library to theme. 🤔

**Comment by eugene-krivobokov** [comment]
Thanks.

> I don't want to include large clipboardjs library to theme.

I share your concern. What about dynamic loading? 
I did so even for mermaid: https://github.com/avito-tech/avito-android/blob/develop/docs/layouts/shortcodes/mermaid.html

**Comment by alex-shpak** [comment]
Well, dynamic linking works for mermaid because there is a shortode that adds it. Enabling copy with empty shortcode will be pretty lame :) I think rather find smaller lib or write minimum required code in vanilla js.

BTW. mermaid is linked from repo in order to support offline/intranet work.

https://github.com/alex-shpak/hugo-book/blob/0811fa03afef332a5aa8377d1667bbfef928137d/assets/clipboard.js
This kinda works, but not for table snippets (with line numbers)

**Comment by jasikpark** [comment]
Would https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText not be adequate? Writing the formatting of the code to be copied to the clipboard would be the only mildly complicated part potentially..

**Comment by jasikpark** [comment]
An example: https://codepen.io/jasikpark/pen/BaQZapz

**Comment by jasikpark** [comment]
And perhaps show the copy-to-clipboard button based on the existence of "navigator.clipboard"?

```
if (window.navigator.clipboard) {
  copyButton.addEventListener('click', copyCode);
  copyButton.classList.remove("hidden");
}
```

**Comment by alex-shpak** [comment]
Some solution has landed.
Clicking code in code-block will select code and copy it to the clicpboard.

**Comment by alex-shpak** [comment]
I used it for a bit, I think I won't add dedicated button, as it looks clean and minimalist now.
Will close issue for now, write here if you want to continue discussion.
