### ISSUE TITLE
Expand shortcode has a layout shift when content is smaller than viewport

### ISSUE THREAD

**Issue by jasikpark** [alex-shpak/hugo-book#310]
When the page is shorter than the viewport on desktop, there is no scrollbar for the page, whereas when the expand shortcode is clicked on and expanded, a scrollbar is added to the document, which means that the entire website is shifted over to the left, which is rather disorienting.

Screenshots:

- Unexpanded expand shortcode:
<img width="1680" alt="Screen Shot 2021-02-17 at 4 13 19 PM" src="https://user-images.githubusercontent.com/10626596/108275008-46d05680-713b-11eb-893b-755e52196588.png">
- Expanded expand shortcode:
<img width="1680" alt="Screen Shot 2021-02-17 at 4 13 26 PM" src="https://user-images.githubusercontent.com/10626596/108275028-4e8ffb00-713b-11eb-802f-a6a5dee93bf7.png">
- Diff between the two images:

![image_diff](https://user-images.githubusercontent.com/10626596/108275049-5780cc80-713b-11eb-94a6-c2f528f32a1c.png)

**Comment by skeezix-de** [comment]
Sure...when you expand your section the right scrollbar is put in place by your browser, thus shrinking the viewport size. It's not a bug...

**Comment by jasikpark** [comment]
So it's intended behavior for the website to shift over to the left when opening an "expand" shortcode?

**Comment by skeezix-de** [comment]
No, but in your case the right scrollbar appears when you expand the section.
There was no need for it to be displayed before expanding the section because everything fit on the screen. It doesn't fit after expanding, so the scrollbar is getting displayed. By this the horizontal space is reduced. The content is centered. So if the content is centered in a reduced horizontal space, it seems to jump.
You can avoid this "jump" when you display the scrollbar all the time. To do this, add a css rule:
body { overflow-y: scroll; }

**Comment by devoto13** [comment]
https://muffinresearch.co.uk/osx-remove-scrollbars-that-appear-when-using-a-mouse/ 🙃
