### ISSUE TITLE
How do I close the content summary  in the posts list?

### ISSUE THREAD

**Issue by yuuuuu422** [alex-shpak/hugo-book#331]
Hi,I was wondering if it might be possible to close the content summary in the posts list.I found that if I didn't use English, the summary would not stop,just like this.
![image](https://user-images.githubusercontent.com/59158328/115104991-d012d680-9f8e-11eb-9d2f-ac0ce25028fe.png)
And I found in the [issues#286](https://github.com/alex-shpak/hugo-book/issues/286),We could use  image thumbnails in the posts list,But still can't stop content summarization.

**Comment by alex-shpak** [comment]
Hi!
I would guess that hugo doesn't cut summary proerly because they are using word count for it.
One solution myght be to insert summary break into page, to cut off summary portion.

Ref:  https://gohugo.io/content-management/summaries/#manual-summary-splitting

Add `<!-- more -->` where you want summary to end.
