### ISSUE TITLE
flexsearch ignores baseURL path leading to 404s

### ISSUE THREAD

**Issue by joernhees** [alex-shpak/hugo-book#363]
Thanks for this nice theme, which we use to render some docs. In our case it ends up in some subdir of a larger page http://example.org/subdir/XYZ .

Today we noticed that search in our case works only until you actually click on one of the results... problem seems to be that the generated search result links don't include the path up to subdir (they point to http://example.org/XYZ ) leading to 404 errors.

So we started experimenting with `baseURL` (`=""` or `="http://example.org/subdir/"`), `relativeURLs` and `canonifyURLs`. We actually tried all combinations, none worked. Some don't find the flexsearch json files it seems, but if they exists, opening them reveals that the links in there are absolute (but host local) links (so they just point to `/XYZ`), which works if you're served from the root dir and not a subdir.

maybe related #333

**Comment by joernhees** [comment]
weird thing though: https://github.com/alex-shpak/hugo-book/blob/c4d69635aff3be7ff54b07b93218d27d0e1ce928/assets/search-data.json#L9
as far as i understand from the docs, this should already include baseURL, no?

**Comment by alex-shpak** [comment]
Hi!
Well, it should work as expected, I think we need to look at your configuration.

if you clone repo and run hugo on example site as
```
hugo serve --themesDir ... --bind=0.0.0.0 --baseURL=http://localhost:1313/example/xyz
```

At least ot works as expected for me.

**Comment by joernhees** [comment]
hmm, i guess if you cannot reproduce then the problem is probably on our side somewhere...

closing this for now, fix is above if others should stumble over the same problem...

our `config.toml` at the moment looks like this:
```
baseURL = "http://example.org/subdir/XYZ"
relativeURLs = false
canonifyURLs = true
title = 'foobar'
theme = 'hugo-book-9'
```

**Comment by rluders** [comment]
Well, sorry folks to "resurrect" this one.

I'm having the same issue. I do have a GitLab Page that is hosted on `https://<user>.pages.domain.com/<repository>`. In this same project I'm using the config (just the part that matters):

```yaml
baseURL: https://user.pages.domain.com/docs
canonifyURLs: true
```

And I need/want to use `canonifyURLs: true` otherwise my images don't get loaded, since I'm using:

```md
![My image][/images/my-image.png]
```

(Doesn't matter if I cant to `images/my-image.png` or make it `relativeURLs: true`... by doing that I do have the images being loaded, or the page assets don't get loaded, or the search doesn't work. One of the options will fail.

So, I was digging into the theme code, and I found and also came to this issue, and I found that @joernhees came to the same solution that I came up with... Just to replace the:

https://github.com/alex-shpak/hugo-book/blob/d5b75f4fb3aaa5c2f0209db4933a55aa634d5dfd/assets/search.js#L8

With:

```js
const searchDataURL = '{{ $searchData.Permalink }}';
```

Solves the issues for all cases (I mean, you are still now able to use:

```yaml
relativeURLs: true
canonifyURLs: false
```

'Cause, it will break some theme assets loading, but all other combinations seem to work... So, I'm submitting a PR to change this line.
