### ISSUE TITLE
normalize.min.css.map 404

### ISSUE THREAD

**Issue by vhbelvadi** [alex-shpak/hugo-book#44]
Local server runs throw a 404 for a `normalize.min.css.map` file. Where is this error coming from? It's not grave in that it only pops up in the background on a local server (in the console) and doesn't appear on a live site.

I tried deleting line 2 in `static/normalize.min.css` in hugo-book but that did nothing. Again, this is not an error, I'm just curious.

**Comment by alex-shpak** [comment]
Hi!

Source map files used to show real source code instead of minified file. Error only should appear when you use dev tools in your browser. I think you can ignore it.

Removing second line `static/normalize.min.css` should resolve 404 error, maybe you didn't see result because of cache.

P.S. In the end, after reading https://github.com/necolas/normalize.css/issues/4 I decided to put `normalize.css` into hugo's sass pipeline with minification.

**Comment by vhbelvadi** [comment]
That’s great. It wasn’t an issue exactly but every time I’d open the inspector it used to bother me. Haha.
