### ISSUE TITLE
issue for folder names in all capital

### ISSUE THREAD

**Issue by lennyleadership** [alex-shpak/hugo-book#454]
I found one folder being named in all capital, such as CGC, is turned out to be Cgc after rendering.

**Comment by alex-shpak** [comment]
Hi!
This is due to this line: 
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/title.html#L10 `| title`

you can force title by setting `.title` in frontmatter like here
https://raw.githubusercontent.com/alex-shpak/hugo-book/master/exampleSite/content/docs/example/table-of-contents/with-toc.md
