### ISSUE TITLE
Hope to add `pagefind` as the default search engine for the theme to increase search speed

### ISSUE THREAD

**Issue by coloraven** [alex-shpak/hugo-book#549]
This theme is exactly what I wanted, but I found that the search speed is too slow during use. I hope to use `pagefind` as the default search engine for the theme to enhance the search speed. I would like to express my gratitude to those who worked hard to develop this theme.

**Comment by alex-shpak** [comment]
Hello!
I can look at it, is there somewhere comparison in search speed between `pagefind` and `flexsearch`?

**Comment by coloraven** [comment]
> Hello! I can look at it, is there somewhere comparison in search speed between `pagefind` and `flexsearch`?
Perhaps I made a mistake. The search engine for this topic is not slow, but it does not support searching with Chinese characters. Therefore, it seems that no results have been found even though the search keyword definitely exists somewhere in the article.

**Comment by loikein** [comment]
> it does not support searching with Chinese characters

Hi @coloraven, I have tested on the `exampleSite` of this theme, and flexsearch does have the ability to search Chinese characters.

<img width="272" alt="image" src="https://github.com/alex-shpak/hugo-book/assets/20618587/e3973696-8ba5-4426-9170-31a83722d710">

I speculate the reason why the lawrefbook's searching functionality does not work is because it is using an old version of the [search-data.json](https://github.com/LawRefBook/lawrefbook.github.io/blob/main/assets/search-data.json). Please see https://github.com/alex-shpak/hugo-book/issues/528 if you want to make a PR over there. They should just delete that `assets` folder and update to newest version of the theme.

---

However, @alex-shpak, the problem I have encountered is that flexsearch only creates one index for one language, and the logic right now for deciding which language it calls is based on the Hugo multilingual mode ([L29 of /layouts/partials/docs/html-head.html](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/html-head.html#L29)). Therefore, for sites with mixed languages (no `Languages` config, but has proper `html lang` attributes), only one language can be searched, which is the `DefaultContentLanguage`.

On the contrary, pagefind can handle multiple languages all at once, without even the need to specify the language. It seems to be able to index any word independently from the language. (I have tested it on my other site with very messed-up settings and mixed languages for multiple pages.)

So, that was a long way to say that I would also really hope that you could consider using pagefind.

**Comment by alex-shpak** [comment]
Hi! with PR https://github.com/alex-shpak/hugo-book/pull/600
theme uses fusejs that should be configurable for multiple languages
