### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by eugenevdm** [alex-shpak/hugo-book#59]
I've fallen in love with this theme and I'm requesting a dark theme. Apologies if this is not the right place to ask for it.

**Comment by alex-shpak** [comment]
Hi! Thank you.
I think dark mode would not be too hard to do, at this moment I'm not sure if I want to add extra complexity, because with all features theme started to grow bigger and bigger, which I want to avoid.

Anyway, most of colors are in `assets/_variables.scss` file, but I want to implement search and refactor menu first. Meanwhile you can tweak sass variables in that file yourself.

**Comment by alex-shpak** [comment]
Hi!
After some though, I think dark theme would not make into core.

But, I made it more easy to implement and created an example how you can make dark theme in your website.

You can create `$WEBSITE/assets/_variables.scss` file and override variables like here: 
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_variables.scss

Result:
![image](https://user-images.githubusercontent.com/5515443/66129287-e72de580-e5ef-11e9-84c4-d1366fe2db2d.png)

**Comment by jamesb93** [comment]
Hi Alex,

It seems that the variables are no longer at that link. It would be nice to know which colours you used specifically and for what elements of the scss. Trying this myself it is easy to get the background and body text to a similar theme but the side panel seems to not change at all no matter where I set the `color: $white;`

**Comment by alex-shpak** [comment]
Hi!
Just uncomment this line
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_variables.scss#L3

I moved variables to separate file
https://github.com/alex-shpak/hugo-book/blob/master/assets/plugins/_dark.scss
